---
permalink: linux-administration/concept_guidelines_for_thesnapdrive_storagedisconnectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, disconnect, command, guidelines 
summary: Befolgen Sie bei Verwendung des Befehls SnapDrive Storage Disconnect die folgenden Richtlinien. 
---
= Richtlinien für den SnapDrive Storage Trennen Befehl
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie diese Richtlinien, wenn Sie die verwenden `snapdrive storage disconnect` Befehl:

* Wenn Sie ein Dateisystem trennen, entfernt SnapDrive für UNIX immer den Mountpoint.
+
Mithilfe von Linux Hosts können Sie mehrere Filesysteme zu einem einzigen Bereitstellungspunkt verbinden. Allerdings erfordert SnapDrive für UNIX einen einzigartigen Bereitstellungspunkt für jedes File-System. Der `snapdrive storage disconnect` Befehl schlägt fehl, wenn Sie es verwenden, um Dateisysteme zu trennen, die an einem einzigen Bereitstellungspunkt angeschlossen sind.

* Wenn Sie den verwenden `-lun` Option, um den Namen einer LUN anzugeben, die Mitglied einer Host-Laufwerksgruppe oder eines Dateisystems ist, die `snapdrive storage disconnect` Befehl schlägt fehl.
* Wenn Sie verwenden `-lun` Option, um den Namen der LUN anzugeben, die nicht durch Multipathing-Software auf dem Host erkannt wird, im `snapdrive storage disconnect` Befehl schlägt fehl.



NOTE: `snapdrive storage disconnect` Befehl schlägt beim Verwenden der RDM LUN fehl, wenn die Mapping-Initiatorgruppe mehr als zwei World Wide Port Names (WWPN) aufweist, in Releases vor SnapDrive 5.2 für UNIX.
