---
permalink: linux-administration/concept_restoring_snapshotcopies_ona_destination_storagesystem.html 
sidebar: sidebar 
keywords: snap, snapdrive, restore, storage, system, snapshot, copy 
summary: Sie können Snapshot-Kopien auf dem Storage-System wiederherstellen, von dem sie erstellt werden. 
---
= Wiederherstellen von Snapshot Kopien auf einem Ziel-Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Snapshot-Kopien auf dem Storage-System wiederherstellen, von dem sie erstellt werden.

Wenn Sie eine Snapshot Kopie auf einem Ziel-Storage-System erstellen, wird die Snapshot Kopie automatisch vom Quellsystem repliziert. Dabei wird sie zum Ziel-Storage-System erstellt. Mit SnapDrive für UNIX können Sie die Snapshot-Kopie auf dem Quell-Storage-System wiederherstellen. Sie können außerdem die Snapshot-Kopie auf dem Ziel-Storage-System wiederherstellen.

Wenn Sie eine einzelne Datei Snap Restore in einer SnapMirror-Beziehung durchführen, dann sollten die Quell- und Ziel-Volume-Namen nicht dieselben sein. SnapDrive für UNIX zeigt die folgende Fehlermeldung an, wenn der Name des Quell- und Ziel-Volume identisch ist:

[listing]
----
0001-636 Command error: Snapdrive cannot restore LUNs on SnapMirror
destination filer volumes: <filer-vol-name>
----
Wenn in SnapDrive 4.0 für UNIX und höher, wenn die rollenbasierte Zugriffssteuerung aktiviert ist, können Sie Snap Restore auf der Einheit vFiler nur durchführen, wenn Sie die Snapshot Restore-Funktion auf der Einheit von vFiler haben.

*Verwandte Informationen*

xref:concept_role_based_access_control_in_snapdrive_for_unix.adoc[Rollenbasierte Zugriffssteuerung in SnapDrive für UNIX]
