---
permalink: linux-administration/concept_snapdrive_for_unix_faces_issue_after_sles_upgrade_from_version_10_to_11.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, suse, upgrade, file, base, device 
summary: 'SnapDrive für UNIX zeigt einen Fehler an, nachdem Sie den SUSE Linux Enterprise Server \(SLES\) von Version 10 auf 11 aktualisiert haben. Sie müssen einen Basisgerätenamen erstellen und das Dateisystem mounten.' 
---
= SnapDrive für UNIX zeigt eine Fehlermeldung an, nachdem SUSE Linux Enterprise Server von Version 10 auf 11 aktualisiert wurde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX zeigt einen Fehler an, nachdem Sie den SUSE Linux Enterprise Server (SLES) von Version 10 auf 11 aktualisiert haben. Sie müssen einen Basisgerätenamen erstellen und das Dateisystem mounten.

Wenn Sie Speichervorgänge ausführen, meldet SnapDrive für UNIX die folgende Fehlermeldung: `0001-791 Admin error: Device /dev/sdc does not have a partition. A single partition is required to support a persistent mount for file system /mnt/testfs. Retry command with '-nopersist' option`



== Behelfslösung

. Verwenden Sie die Optionen `-fs` Und `-nopersist` So zeichnen Sie den Namen des Basisgeräts auf, wie im folgenden Beispiel gezeigt:
+
`*IBMX336-250-111:/etc/udev/rules.d # snapdrive storage connect -fs /mnt/testfs -lun f3020-207-11:/vol/san1/lun200_0 -nolvm -nopersist*``

+
Ein Dateisystem wird nicht wie erwartet erstellt, aber der Name des Basisgeräts wird aufgezeichnet (in diesem Fall `/dev/sdc`).

. Erstellen Sie die `mkdir --p /mnt/testfs` Verzeichnis im Basisgerätenamen.
. Laufen `blkid`.
. Geben Sie Folgendes an:
+
`*UUID=239ae9a1-75fd-4faf-b9f4-a0b80bf7b62c /mnt/testfs ext3*`

. Mounten des Dateisystems:
+
`*#mount /mnt/testfs*``

. Anzeigen der Speicheroptionen:
+
`*#snapdrive storage show -fs /mnt/testfs3*`


