---
permalink: linux-administration/concept_guidelines_fordisconnectingsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, snapshot, copy, lun, storage, nfs 
summary: Nachfolgend sind die Richtlinien aufgeführt, um eine Snapshot Kopie für LUNs, Storage-Einheiten oder NFS Directorys zu trennen. 
---
= Richtlinien zum Trennen von Snapshot Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachfolgend sind die Richtlinien aufgeführt, um eine Snapshot Kopie für LUNs, Storage-Einheiten oder NFS Directorys zu trennen.

* Wenn Sie ein Dateisystem trennen, entfernt SnapDrive für UNIX immer den Mountpoint.
* Mithilfe von Linux Hosts können Sie mehrere Filesysteme zu einem einzigen Bereitstellungspunkt verbinden. Allerdings erfordert SnapDrive für UNIX einen einzigartigen Bereitstellungspunkt für jedes File-System. Der `snapdrive snap disconnect` Befehl schlägt fehl, wenn Sie es verwenden, um Dateisysteme zu trennen, die an einem einzigen Bereitstellungspunkt angeschlossen sind.
* Um die Auswirkungen der Snapshot-Verbindung rückgängig zu machen, verwenden Sie den Befehl Snapshot Trennen.
* Wenn Sie die einstellen `enable-split-clone` Wert der Konfigurationsvariable auf `on` Oder `sync` Während der Snapshot-Verbindung und `off` Während der Abtrennung von Snapshot löscht SnapDrive für UNIX nicht das ursprüngliche Volume oder die LUN, die sich in der Snapshot Kopie befindet.

