---
permalink: linux-administration/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, shot, list, command 
summary: Mit dem Befehl SnapDrive Snap show or list werden der Name des Storage-Systems angezeigt, zu dem die Snapshot Kopie erstellt wird, der Host-Name, das Datum und die Zeit usw. 
---
= Anzeigen einer Snapshot Kopie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Befehl `snapdrive snap show` Oder `list` Zeigt den Namen des Storage-Systems an, auf dem die Snapshot Kopie erstellt wird, den Host-Namen, das Datum und die Uhrzeit usw.

.Schritte
. Geben Sie die folgende Befehlssyntax ein, um eine Snapshot-Kopie anzuzeigen:
+
`*snapdrive snap show [-snapname] long_snap_name [snap_name...] [-verbose]*`



Dieser Vorgang wird mindestens die folgenden Informationen über die Snapshot Kopie angezeigt:

* Der Name des Storage-Systems, auf dem die Snapshot Kopie erstellt wird
* Der Name des Hosts, der die Snapshot Kopie erstellt hat
* Der Pfad zu den LUNs auf dem Storage-System
* Das Datum und die Uhrzeit der Erstellung der Snapshot Kopie
* Der Name der Snapshot Kopie
* Die Namen der in der Snapshot-Kopie enthaltenen Festplattengruppen


*Beispiel*: Die folgenden Beispiele sind Beispiele von `snapdrive snap show` Befehl:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Beispiel*: In diesem Beispiel wird ein Platzhalter verwendet, um Informationen über die verfügbaren Snapshot Kopien auf einem bestimmten Volume anzuzeigen:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Beispiel*: Dieses Beispiel zeigt eine Snapshot-Kopie eines NFS-gemounteten Verzeichnisbaums auf einem Linux Host unter Verwendung des SnapDrive Snap list Befehls mit dem `- verbose` Option:

[listing]
----
# snapdrive snap list -fs /mnt/acctfs1 -v
snap name host date
snapped
------------------------------------------------------------------
----------
besser:/vol/vol1:acctfs-s1 childs Aug 8 18:58
/mnt/acctfs1
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: acctfs-s1 file system: type: nfs mountpoint:
/mnt/acctfs1
filer dir: besser:/vol/vol1
----
*Beispiel*: Dieses Beispiel führt den SnapDrive Snap show Befehl auf einem Linux Host aus:

[listing]
----
# snapdrive snap show -snapname surf:/vol/vol1:swzldg5snapped
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
#
# ./linux/ix86/snapdrive snap show -v -snapname
surf:/vol/vol1:bagel5snapped >
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: bagel5snapped
Volume Manager: linuxlvm 1.0.3
disk group: dg5
host volume: vol1
host volume: vol2
host volume: vol3
lun path dev paths
-------------------------------------------------------
surf:/vol/vol1/glk19 /dev/sdu
----
*Beispiel*: Die folgenden Beispiele verwenden Platzhalter:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Beispiel*: In diesem Beispiel ist die Verwendung eines Platzhalters ungültig, da der Platzhalter in der Mitte des Namens liegt, anstatt am Ende platziert zu werden:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----