---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: Um Multipathing in SnapDrive für UNIX zu verwenden, müssen Sie Schritte einschließlich der Installation und dem Starten des HBA durchführen. Wenn Sie eine Multipathing-Lösung von anderen Herstellern verwenden, müssen Sie die Software und das Anwendungspaket von der Website des HBA-Anbieters herunterladen. 
---
= Aktivieren von Multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Multipathing in SnapDrive für UNIX zu verwenden, müssen Sie Schritte einschließlich der Installation und dem Starten des HBA durchführen. Wenn Sie eine Multipathing-Lösung anderer Anbieter verwenden, müssen Sie die Software und das Applikationspaket auf der Website des HBA-Anbieters herunterladen.

Ihr System muss aktuelle Versionen von FC und iSCSI Systemkomponenten ausführen.

http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]

.Schritte
. Installieren Sie die unterstützten HBAs, bevor Sie die entsprechende Host Utilities-Software installieren.
+

NOTE: SnapDrive für UNIX unterstützt HBAs verschiedener Anbieter.

. Starten Sie den HBA-Service.
+
Wenn der HBA-Service nicht ausgeführt wird, wird die folgende Fehlermeldung angezeigt, wenn Sie SnapDrive für UNIX Befehle ausführen, z. B. `snapdrive storage create` Und `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
Sie müssen überprüfen, ob die erforderliche Anzahl an Pfaden in der Ausführung vorhanden ist. Sie können die Pfade mit überprüfen `sanlun` Dienstprogramm, das in der Software Host Utilities enthalten ist. Beispielsweise können Sie in der FC-Multipathing-Konfiguration die verwenden `sanlun fcp show adapter -v` Befehl.

+
Im folgenden Beispiel sind zwei HBA-Ports (fcd0 und fcd1) mit dem Host verbunden, die betriebsbereit sind (Portstatus). Sie können nur einen HBA oder iSCSI-Initiator haben und Sie müssen Multipathing konfigurieren, indem Sie mehr als einen Pfad zu den Ziel-LUNs bereitstellen.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Wenn Multipathing auf einem Host aktiviert ist, sind für dieselbe LUN mehrere Pfade sichtbar. Sie können das verwenden `sanlun lun show all` Befehl zum Überprüfen der Pfade: Im folgenden Beispiel können Sie mehrere Pfade zu derselben LUN finden (`fish: /vol/vol1/lun`):

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. Wenn eine Multipathing-Lösung eines Drittanbieters von SnapDrive für UNIX oder Host Utilities unterstützt wird, laden Sie das HBA-Treibersoftwarepaket und das Anwendungspaket von der Website des HBA-Anbieters herunter.*QLogic*: Für QLogic HBAs finden Sie unter http://support.qlogic.com/[]. Wählen Sie bei OEM-Modellen NetApp aus. Suchen Sie die Treiberversion, die in der Support Matrix aufgeführt ist, und laden Sie sie herunter. * Emulex:* für Emulex HBAs, gehen Sie zu http://www.emulex.com/ts/index.html[]. Wählen Sie unter Downloads NetApp aus. Suchen Sie die Treiberversion, die in der Support Matrix aufgeführt ist, und laden Sie sie herunter. Laden Sie auch das Emulex Anwendungspaket von demselben Speicherort herunter.
+
Wenn Sie einen QLogic Adapter mit FC-Konnektivität verwenden, laden Sie das QLogic Scan Skript von der QLogic Website herunter und kopieren Sie es in die `/root` Pfad (z. B. `/root/dynamic-lun-rescan.sh`). Das QLogic Scan Skript fragt nach Bestätigung des Benutzers; SnapDrive für UNIX hängt möglicherweise an dieser Bestätigungsphase auf unbestimmte Zeit ab. Sie können diese Bestätigung vermeiden, indem Sie die Variable einstellen `_QL_DISABLE_WARNING_` Bis `1` Im Skript.

+
In früheren Versionen von SnapDrive für UNIX wurden herstellerspezifische SCSI-Rescan-Skripte verwendet, um LUNs über FC zu scannen und somit das anbieterspezifische Skript auf die Kopie zu übertragen `/root/dynamic-lun-rescan.sh`. Diese wurde bis zum RHEL 5U3 verfügbar gemacht.

+
Für RHEL 5U4/ SLES 10SP2 und neuere Versionen ist das Sccan-Skript derzeit im verfügbar `/usr/bin` Verzeichnis. Falls das ScriptScript nicht im Verzeichnis verfügbar ist, ist es zusammen mit dem vorhanden `sg3_utils` Paket.

+

NOTE: Sie müssen sicherstellen, dass die `sg3_utils` Und `sg3_utils-libs` Bibliotheken sind für die Versionen Red hat Enterprise Linux (RHEL) und Oracle Enterprise Linux (OEL) verfügbar. Allerdings das `sg3_utils` Bibliotheken sind für SUSE Linux Enterprise Server (SLES)-Version im verfügbar `scsci utility.rpm` Paket.

. Zonen der Host-HBA-Ports und der Ziel-Ports in einer FC-Konfiguration mit der Switch-Zoning-Konfiguration.
. Installieren und richten Sie den entsprechenden FC-Switch ein.
. Stack-Anforderungen für SnapDrive für UNIX prüfen.
. Installation oder Upgrade von SnapDrive für UNIX
. Überprüfen Sie die Installation von SnapDrive für UNIX.
. Suchen Sie das `snapdrive.conf` Dateipfad:
. Konfigurieren Sie die folgenden Konfigurationsvariablen in der `snapdrive.conf` Datei:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Bei jedem Host hängen Multipathing-Typ, Transporttyp, Filesystem und Volume-Manager-Typ von einander ab. In der folgenden Tabelle werden alle möglichen Kombinationen beschrieben:

+
|===
| Host-Plattform | Standardtransportart | Multipathing-Typ | Fstype | Vmtype 


 a| 
Linux
 a| 
iscsi
 a| 
Nativempio
 a| 
Ext4 oder ext3
 a| 
lvm



 a| 
iscsi
 a| 
Keine
 a| 
Ext4 oder ext3
 a| 
lvm



 a| 
FCP
 a| 
Keine
 a| 
Ext4 oder ext3
 a| 
lvm



 a| 
FCP
 a| 
Nativempio
 a| 
Ext4 oder ext3
 a| 
lvm

|===
+
Die vorstehende Tabelle gibt die unterstützten Werte des an `_multipathing-type_`, `_default-transport_`, `_fstype_`, und `_vmtype_` Konfigurationsvariablen.

+

NOTE: Wenn das Transportprotokoll lautet `iSCSI`, Und der Multipathing-Typ wird als festgelegt `none`, Sie sollten den Multipath Daemon stoppen und SnapDrive für UNIX Befehle ausführen.



. Speichern Sie die `snapdrive.conf` Datei:
+
SnapDrive für UNIX prüft diese Datei automatisch jedes Mal, wenn sie startet. Sie müssen den SnapDrive for UNIX Daemon neu starten, damit die Änderungen wirksam werden.



*Verwandte Informationen*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[SnapRestore- und Snapconnect-Vorgänge funktionieren nach der Migration des Multipathing-Typs nicht in Linux]

http://mysupport.netapp.com["NetApp Support"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Installationsleitfaden Für Linux Unified Host Utilities 7.1"]
