---
permalink: linux-administration/task_enabling_thin_provisioning_for_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, lun, thin, provisioning, reservation, space 
summary: Sie können SnapDrive für UNIX für Thin Provisioning auf Ihrem Storage-System verwenden. Thin Provisioning wird auch als Speicherplatzreservierung bezeichnet. 
---
= Aktivieren von Thin Provisioning für LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapDrive für UNIX für Thin Provisioning auf Ihrem Storage-System verwenden. Thin Provisioning wird auch als Speicherplatzreservierung bezeichnet.

.Schritt
. Stellen Sie die ein `space-reservations-enabled` Wert der Konfigurationsvariable auf `on`.
+
Sie können Thin Provisioning auch mit der aktivieren `-reserve` Und `-noreserve` Parameter.

+
Parameter überschreiben den im angegebenen Wert `-space-reservations-enabled` Variabel.

+
Sie können verwenden `-reserve` Und `-noreserve` Mit den folgenden Befehlen zum Aktivieren oder Deaktivieren der LUN-Reservierung:

+
** `snapdrive storage create`
** `snapdrive storage resize`
** `snapdrive snap connect`
** `snapdrive snap restore`


+
Standardmäßig ermöglicht SnapDrive für UNIX die Speicherplatzreservierung für neue oder neue Storage-Erstellungsvorgänge. Für Snap Restore und Snap Connect Vorgänge wird die in der Snapshot Kopie vorhandene Speicherplatzreservierung verwendet, wenn das `-reserve` Oder `-noreserve` Parameter werden nicht in der Befehlszeile angegeben oder wenn der Wert in der Konfigurationsdatei nicht kommentiert ist.


