---
permalink: linux-administration/task_changing_asnapshot_copyname.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, rename, command, source, name 
summary: Sie können den Namen einer Snapshot Kopie mit dem Befehl SnapDrive Snap umbenennen. Beim Snapshot-Umbenennen wird der Name der Snapshot-Quell-Kopie in den Namen geändert, der vom Zielargument angegeben wurde. 
---
= Der Name einer Snapshot Kopie wird geändert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Namen einer Snapshot Kopie mit ändern `snapdrive snap rename` Befehl. Beim Snapshot-Umbenennen wird der Name der Snapshot-Quell-Kopie in den Namen geändert, der vom Zielargument angegeben wurde.

Bevor Sie diese Syntax ausführen, müssen Sie die in diesem Befehl genannten Optionen, Schlüsselwörter und Argumente verstehen.

.Schritte
. Geben Sie den folgenden Befehl ein, um den Namen der Snapshot Kopie zu ändern:
+
`*snapdrive snap rename [-snapname] _old_long_snap_name new_snap_name_ [-force [-noprompt]]*`



Im Folgenden finden Sie Beispiele für `snapdrive snap rename` Befehl. Die erste Befehlszeile enthält das `-force` Option, weil eine Snapshot Kopie mit dem Namen vorhanden ist `new snapshot` Kopie ist bereits vorhanden. Im zweiten Beispiel verwenden beide Namen von Snapshot Kopien die lange Form des Namens, jedoch werden sie beide für dasselbe Storage-System-Volume aufgelöst.

[listing]
----
snapdrive snap rename -force filer1:/vol/vol1:oldsnap new snapshot
----
[listing]
----
snapdrive snap rename filer1:/vol/vol1:FridaySnap filer1:/vol/vol1:Snap040130
----