---
permalink: linux-administration/task_configuring_management_and_data_interfaces_for_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, management, configure, data, interface, nfs, traffic 
summary: Sie können mehrere Datenschnittstellen für eine einzelne Managementoberfläche in einer NFS-Umgebung konfigurieren, sodass sich der Management-Datenverkehr vom Datenverkehr in Ihrem Storage-System trennen lässt. 
---
= Konfiguration von Management- und Datenschnittstellen für ein Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mehrere Datenschnittstellen für eine einzelne Managementoberfläche in einer NFS-Umgebung konfigurieren, sodass sich der Management-Datenverkehr vom Datenverkehr in Ihrem Storage-System trennen lässt.

.Schritte
. Legen Sie die Konfiguration für die neue Managementoberfläche fest:
+
`*snapdrive config set root*`

+
[listing]
----
# snapdrive config set root f3050-197-91
Password for root:
Retype password:
----
+
Im Folgenden finden Sie ein Beispiel für eine Storage Virtual Machine (SVM, ehemals Vserver).

+
[listing]
----
# snapdrive config set vsadmin clstr-vs2
Password for vsadmin:
Retype password:
----
. Konfigurieren Sie die Datenschnittstelle für die neue Managementoberfläche:
+
`*snapdrive config set*`

+
[listing]
----
# snapdrive config set -mgmtpath f3050-197-91 f3050-220-91#
----
+
Mit dem vorherigen Befehl `f3050-197-191` Ist die Managementoberfläche und `f3050-220-91` Ist die Datenschnittstelle.

+
Das folgende Beispiel zeigt eine SVM.

+
[listing]
----
snapdrive config set -mgmtpath clstr-vs2  clstr-vs2-2
system name   management interface   datapath interface
-------------------------------------------------------
clstr-vs2     10.72.220.203          10.72.221.155
----
+
In der Ausgabe, `10.72.220.203` Ist die Managementoberfläche und `10.72.221.155` Ist die Datenschnittstelle.


