---
permalink: linux-administration/task_adding_host_entries_for_new_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, host, entries, lun, command 
summary: Mit SnapDrive für UNIX können Sie eine bestimmte Anzahl neuer LUNs erstellen. SnapDrive für UNIX bietet hierfür spezifische Befehle. 
---
= Hinzufügen von Hosteinträgen für neue LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapDrive für UNIX können Sie eine bestimmte Anzahl neuer LUNs erstellen. SnapDrive für UNIX bietet hierfür spezifische Befehle.

Stellen Sie sicher, dass der Host bereit ist, eine bestimmte Anzahl neuer LUNs zu erstellen. Diese LUNs befinden sich auf einem Speichersystem, das dem Host zugeordnet ist.

.Schritte
. `snapdrive config prepare luns -count count`
+
`-count` Ist die Anzahl der neuen LUNs, für die der Host vorbereitet werden soll.

+
Unter Linux fügt dieser Befehl eine neue hinzu `/dev/sg` Gerätedatei für jede potenzielle LUN, für die derzeit keine Gerätedatei verfügbar ist.

+
[NOTE]
====
Wenn Sie den manuell bearbeitet haben `/kernel/drv/lpfc.conf` Datei für persistente Bindungen, stellen Sie sicher, dass der Eintrag FC-bind-WWPN nach ist

`# BEGIN: LPUTIL-managed Persistent Bindings`.

====

