---
permalink: linux-administration/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file, name 
summary: Wenn Sie eine Protokolldatei aktivieren möchten, geben Sie einen Dateinamen als den Wert im Namenspaar der Protokolldatei an, die Sie aktivieren möchten. Wenn Sie eine Datei deaktivieren möchten, geben Sie keinen Wert für den Parameter Protokolldateiname ein. 
---
= Aktivieren und Deaktivieren von Protokolldateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine Protokolldatei aktivieren möchten, geben Sie einen Dateinamen als den Wert im Namenspaar der Protokolldatei an, die Sie aktivieren möchten. Wenn Sie eine Datei deaktivieren möchten, geben Sie keinen Wert für den Parameter Protokolldateiname ein.

Sie müssen sich als Root-Benutzer angemeldet haben.

.Schritte
. Öffnen Sie das `snapdrive.conf` Datei in einem Texteditor.
. Wählen Sie die entsprechende Option, um eine Protokolldatei zu aktivieren oder zu deaktivieren.
+
|===
| Ihr Ziel ist | Dann... 


 a| 
*Aktivieren Sie eine Protokolldatei*
 a| 
 Specify a file name as the value in the name-value pair of the log file you want to enable. SnapDrive for UNIX only writes log files if it has the name of a file to write to. The default names for the log files are as follows:
** Prüfprotokoll: `sd-audit.log`
** Wiederherstellungsprotokoll: `sd-recovery.log`
** Trace-Protokoll: `sd-trace.log`



NOTE: Der Pfad zu diesen Dateien kann je nach Ihrem Host-Betriebssystem variieren.



 a| 
*Eine Protokolldatei* deaktivieren
 a| 
 Do not enter a value for the log file name parameter. If you do not supply a value, there is no file name to which SnapDrive for UNIX can write the log information.
*Beispiel* in diesem Beispiel wird die Logdatei deaktiviert. `audit-log-file=""`

|===
. Speichern Sie die `snapdrive.conf` Datei, nachdem Sie alle Änderungen vorgenommen haben.
+
SnapDrive für UNIX prüft diese Datei automatisch jedes Mal, wenn sie startet. Sie müssen den SnapDrive for UNIX Daemon neu starten, damit die Änderungen wirksam werden.


