---
permalink: aix/concept_considerations_when_working_with_snapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, considerations, snapshot, copy 
summary: Bei der Verwendung einer Snapshot Kopie sollten Sie jedoch beachten, dass SnapDrive für UNIX nur mit erstellten Snapshot Kopien arbeitet oder dass Snapshot Kopien automatisch vom Storage-System zum Host repliziert werden usw. 
---
= Überlegungen beim Arbeiten mit Snapshot Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Verwendung einer Snapshot Kopie sollten Sie jedoch beachten, dass SnapDrive für UNIX nur mit erstellten Snapshot Kopien arbeitet oder dass Snapshot Kopien automatisch vom Storage-System zum Host repliziert werden usw.

Bei der Arbeit mit Snapshot Vorgängen sollten Sie Folgendes beachten:

* SnapDrive für UNIX funktioniert nur mit Snapshot Kopien, die er erstellt.
+
Es können keine Snapshot Kopien wiederhergestellt werden, die nicht erstellt wurden.

* Wenn Sie eine Snapshot Kopie auf einem Ziel-Storage-System erstellen, wird die Snapshot Kopie automatisch aus dem Quell-Storage-System repliziert, auf dem sie im Ziel-Storage-System erstellt wird.
+
Mit SnapDrive für UNIX können Sie die Snapshot-Kopie auch auf dem Ziel-Storage-System wiederherstellen.

* Die Verbindung zum ursprünglichen Host erfolgt, wenn Sie das verwenden `snapdrive snap connect` Befehl zum Herstellen einer Verbindung zu einer Snapshot-Kopie an einem neuen Speicherort auf demselben Host, auf dem sie zuletzt verbunden war (oder noch verbunden ist).
* Die Snapshot Unterstützung von Storage-Einheiten, die mehrere Storage-System-Volumes oder mehrere Storage-Systeme umfassen, beschränkt sich auf Konfigurationen, die keinen Frostvorgang im Software Stack ermöglichen.
* Wenn Sie das Volume über das NFS-Protokoll exportieren, müssen Sie die Option „anonyme Benutzer-ID“ auf 0 setzen, damit die Befehle „SnapDrive für UNIX“ funktionieren.
* Wenn zwei JFS-Dateisysteme (JFS und JFS2) in einer einzigen Laufwerksgruppe vorhanden sind, unterstützt SnapDrive für UNIX nur Vorgänge für das JFS2-Dateisystem.
* Mit SnapDrive für UNIX können Sie Snapshot Kopien einer gleichzeitigen Volume-Gruppe erstellen und mit denselben Eigenschaften klonen oder wiederherstellen.
* Ein Single File SnapRestore (SFSR) Vorgang, gefolgt sofort von der Erstellung einer Snapshot Kopie schlägt fehl.
+
Sie müssen den Vorgang nach einiger Zeit wiederholen. Weitere Informationen finden Sie im link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html["Leitfaden für das Management von logischem Clustered Data ONTAP Storage"].


