---
permalink: aix/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, example, autosupport, message, support 
summary: SnapDrive für UNIX bietet Beispiele für verschiedene Szenarien. Der Inhalt einer AutoSupport-Nachricht in allen Beispielen ist im Wesentlichen identisch, unabhängig von Ihrem Betriebssystem. 
---
= Beispiele für AutoSupport-Meldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX bietet Beispiele für verschiedene Szenarien. Der Inhalt einer AutoSupport-Nachricht in allen Beispielen ist im Wesentlichen identisch, unabhängig von Ihrem Betriebssystem.

Beispiel: Hinzufügen eines neuen Storage-Systems

Das folgende Beispiel ist eine Meldung, die von einem Host mit dem Namen gesendet wird `_aix207-116_`:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="ohio configured"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Beispiel: Den Daemon neu starten

SnapDrive für UNIX sendet die folgende AutoSupport Meldung an das Speichersystem, wenn Sie den Daemon neu starten:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
SnapDrive für UNIX sendet die folgende AutoSupport Meldung an das Speichersystem, wenn eine Speicherverbindung fehlschlägt:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="4"
        category="storage connect failed"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp,1384: LUN /vol/vol0/test1 on storage system ohio already mapped to initiators in igroup aix207-116_fcp_SdIg at ID 0."/
----
SnapDrive für UNIX sendet im Fall von die folgende AutoSupport Meldung an das Storage-System `snap create` Operation erfolgreich:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp, snapshot_name=snap1"
----