---
permalink: aix/concept_disconnecting_a_filespec.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, file, specification, filespec 
summary: Sie können eine Dateispezifikation trennen. Im folgenden Beispiel wird beschrieben, wie Sie diesen Vorgang abschließen können. 
---
= Trennen einer Dateispezifikation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Dateispezifikation trennen. Im folgenden Beispiel wird beschrieben, wie Sie diesen Vorgang abschließen können.

Das Layout von `/mnt/fs1_0` Wird im Folgenden angegeben.

[listing]
----
# snapdrive storage show -fs /mnt/fs_1_0 -capabilities
raw device: /dev/sde1   mount point: /mnt/fs_1_0 (persistent) fstype jfs2
allowed operations: all

device filename    adapter  path    size    proto   state   clone         lun path                                                         backing snapshot
----------------   -------  ----    ----    -----   -----   -----         --------                                                         ----------------
/dev/sde              -      P      100m    iscsi   online  flex-clone    homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1    vol1:snap2
----
Die folgende Ausgabe zeigt, wie das Dateisystem getrennt werden kann `/mnt/fs_1_0`:

[listing]
----
#snapdrive snap disconnect -fs /mnt/fs_1_0
 delete file system /mnt/fs_1_0
- fs /mnt/fs_1_0 ... deleted
         - LUN homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1 ... disconnected
         - deleting volume clone ... homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot  done
----
Nach dem Trennen des Dateisystems `/mnt/fs_1_0`, SnapDrive für UNIX löscht auch das geklonte Volume `Snapdrive_vol1_0_volume_clone_from_snap2_snapshot`, Wenn die folgenden Bedingungen erfüllt sind:

* Das Volume enthält keine zugeordneten LUNs
* Es sind keine neuen LUNs vorhanden
* Es sind keine neuen Snapshot Kopien vorhanden


*Löschen eines FlexClone nicht erstellt von SnapDrive für UNIX*: SnapDrive für UNIX erlaubt nicht das Löschen von FlexClone nicht von ihm erstellt.
