---
permalink: aix/concept_what_the_web_service_and_daemon_are.html 
sidebar: sidebar 
keywords: snap snapdrive, daemon, web, service 
summary: 'Der SnapDrive für UNIX Webservice bietet eine einheitliche Schnittstelle für alle NetApp SnapManager und Produkte von Drittanbietern zur nahtlosen Integration mit SnapDrive für UNIX. Um Befehle der Befehlszeilenschnittstelle \(CLI\) in SnapDrive für UNIX zu verwenden, müssen Sie den Daemon starten.' 
---
= Was der Webdienst und der Daemon sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der SnapDrive für UNIX Webservice bietet eine einheitliche Schnittstelle für alle NetApp SnapManager und Produkte von Drittanbietern zur nahtlosen Integration mit SnapDrive für UNIX. Um die Befehle der Befehlszeilenschnittstelle (CLI) in SnapDrive für UNIX zu verwenden, müssen Sie den Daemon starten.

Verschiedene NetApp SnapManager Produkte verwenden die Befehlszeilenschnittstelle (CLI) zur Kommunikation mit SnapDrive für UNIX. Die Verwendung der CLI schränt die Performance und Managebarkeit von SnapManager und SnapDrive für UNIX ein. Wenn Sie den SnapDrive for UNIX Daemon verwenden, arbeiten alle Befehle als eindeutigen Prozess. Der Daemon Service hat keine Auswirkungen auf die Verwendung von SnapDrive für UNIX Befehlen.

Der Webservice SnapDrive für UNIX ermöglicht die nahtlose Integration von Drittanbieterapplikationen mit SnapDrive für UNIX. Sie arbeiten mithilfe von APIs mit SnapDrive für UNIX zusammen.

Beim Starten des Daemon überprüft SnapDrive for UNIX Daemon zunächst, ob der Daemon ausgeführt wird. Wenn der Daemon nicht ausgeführt wird, startet er den Daemon. Wenn der Daemon bereits ausgeführt wird und Sie versuchen, ihn zu starten, zeigt SnapDrive für UNIX die Meldung an:

`snapdrive daemon is already running`

Sie können den Status des Daemon überprüfen, um zu ermitteln, ob SnapDrive für UNIX ausgeführt wird oder nicht. Sie sollten den Status überprüfen, bevor Sie sich entscheiden, den Daemon zu starten. Wenn ein anderer Benutzer als der Root-Benutzer versucht, den Status zu überprüfen, prüft SnapDrive für UNIX die Anmeldeinformationen des Benutzers und zeigt die Meldung an:

`snapdrive daemon status can be seen only by root user`

Wenn Sie versuchen, den Daemon zu stoppen, überprüft SnapDrive für UNIX Ihre Anmeldedaten. Wenn Sie ein anderer Benutzer als Root-Benutzer sind, zeigt SnapDrive für UNIX die Meldung an

`snapdrive daemon can be stopped only by root user`

Nachdem Sie den Daemon angehalten haben, müssen Sie den SnapDrive for UNIX Daemon neu starten, damit Änderungen an der Konfigurationsdatei oder an einem beliebigen Modul wirksam werden. Wenn ein anderer Benutzer als der Root-Benutzer versucht, den SnapDrive für UNIX Daemon neu zu starten, überprüft SnapDrive für UNIX die Anmeldeinformationen des Benutzers und zeigt die Meldung an

`snapdrive daemon can be restarted only by root user`
