---
permalink: aix/reference_storage_provisioning_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, provisioning, command, line 
summary: Einige SnapDrive for UNIX Befehle werden für die Storage-Provisionierung verwendet. 
---
= Befehlszeilen für die Storage-Bereitstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einige SnapDrive for UNIX Befehle werden für die Storage-Provisionierung verwendet.

Die folgenden Befehlszeilenoptionen werden für die Storage-Bereitstellung verwendet:

|===
| Betrieb | Befehlszeilenoption 


 a| 
Erstellen
 a| 
`snapdrive storage create-lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [{ -dg | -vg } _dg_name_] [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }][-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create {-lvol | -hostvol} _file_spec_ [{-dg | -vg} _dg_name_]{-dgsize | -vgsize} _size_-filervol _long_filer_path_ [{-noreserve | -reserve}] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create -fs _file_spec_ -nolvm [-fsopts options ] [-mntopts options] [-nopersist] { -lun _long_lun_name_ | -filervol _long_filer_path_ } -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -filervol _long_filer_path_ -dgsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }]`

[NOTE]
====
Sie können jedes beliebige Format für das verwenden `-file_spec` Argument, abhängig vom Storage-Typ, den Sie erstellen möchten. (Denken Sie daran `-dg` Ist ein Synonym für `-vg`, und `-hostvol` Ist ein Synonym für `-lvol`.)

Verwenden Sie dieses Format, um ein Dateisystem direkt auf einer LUN zu erstellen: `-fs _file_spec_ [-nolvm -fs _type_] [-fsops _options_] [-mntopts _options_] [-vmtype _type_]`

Verwenden Sie zum Erstellen eines Dateisystems, das eine Laufwerksgruppe oder ein Host-Volume verwendet, folgendes Format: `-fs _file_spec_ [-fstype _type_] [-fsopts _options_] [-mntops _options_] [-hostvol _file_spec_] [-dg _dg_name_] [-vmtype _type_]`

Um ein logisches oder Host-Volume zu erstellen, verwenden Sie dieses Format: `[-hostvol _file_spec_] [-dg _dg_name_] [-fstype _type_] [-vmtype _type_]`

Um eine Laufwerksgruppe zu erstellen, verwenden Sie dieses Format: `-dg _dg_name_ [-fstype _type_] [-vmtype _type_]`

====


 a| 
Verbinden
 a| 
`snapdrive storage connect -fs _file_spec -nolvm_ -lun _long_lun_name_ [-igroup _ig_name_ [_ig_name ..._]] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name ..._] [-igroup _ig_name_ [_ig_name ..._]][-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name ..._][-igroup _ig_name_ [_ig_name ..._]][-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name..._][-vmtype _type_]`



 a| 
`snapdrive storage connect -fs_file_spec_ {-hostvol | -lvol} _file_spec_ -lun _long_lun_name_ [_lun_name..._] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
Trennen Sie Die Verbindung
 a| 
`snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`



 a| 
`snapdrive storage disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ ...] ...] [-full] [-fstype _type_] [-vmtype _type_]`



 a| 
Größe Ändern
 a| 
`snapdrive storage resize {-dg | -vg} _file_spec_ [_file_spec_ ...]{-growby | -growto} _size_ [_-addlun_ [-igroup _ig_name_ [_ig_name ..._]]] [{ -reseserve | -noreserve }]] [-fstype _type_] [-vmtype _type_]`



 a| 
Anzeigen/Liste
 a| 
`snapdrive storage { show | list } -filer _filername_ [_filername ..._] [-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } -filervol _long_filer_path_ [_filer_path..._][-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } {-all | device} [-capabilities]`



 a| 
`snapdrive storage show [-verbose] {-filer _filername_ [_filername..._] | -filervol _volname_ [_volname..._]} [-capabilities]`



 a| 
`snapdrive storage { show| list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-quiet] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -vg | -dg | -fs | -lvol |-hostvol } _file_spec_ [_file_spec ..._] [{ -vg | -dg | -fs | -lvol | -hostvol } _file_spec_ [_file_spec ..._]] [-verbose] [-quiet [-fstype _type_] [-vmtype _type_] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -filer _filer_name_ [_filer_name_ ...] | -filervol _long_filer_path_ [_filer_path ..._] } [-verbose] [-capabilities] [-quiet]`



 a| 
`snapdrive storage { show | list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-status] [-fstype _type_] [-vmtype _type_] [-capabilities] [-quiet]`



 a| 
Löschen
 a| 
`snapdrive storage delete [-lun] _long_lun_name_ [lun_name...] [-fstype type] [-vmtype type]`



 a| 
`snapdrive storage delete [-vg | -dg | -fs | -lvol | -hostvol] _file_spec_ [_file_spec ..._] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._] ...] [-full] ] [-fstype type] [-vmtype type]`

|===
*Verwandte Informationen*

xref:reference_command_line_arguments.adoc[Befehlszeilenargumente]
