---
permalink: aix/reference_stack_requirements.html 
sidebar: sidebar 
keywords: snap, snapdrive, stack, requirement 
summary: 'SnapDrive für UNIX erfordert ein Host-Betriebssystem, Host-Filesysteme, NFS, Volume-Manager, FC- oder iSCSI-Host Utilities, Lizenzen für Storage-Systeme, ONTAP Software, MultiStore Software und Internet Protocol \(IP\)-Zugriff. SnapDrive für UNIX hat darüber hinaus bestimmte Stack-Anforderungen, die das Unternehmen erfüllen muss.' 
---
= Stack-Anforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX erfordert ein Host-Betriebssystem, Host-Filesysteme, NFS, Volume Manager, FC- oder iSCSI-Host Utilities, Lizenzen für Storage-Systeme, ONTAP Software, MultiStore Software und IP-Zugriff (Internet Protocol). SnapDrive für UNIX hat darüber hinaus bestimmte Stack-Anforderungen, die das Unternehmen erfüllen muss.



== Host-seitige Einheiten

Nachfolgend eine Liste der Host-seitigen Einheiten:

* Das Host-Betriebssystem
* Einen Volumenmanager
* File-System
* AIX Host Utilitys




== SnapDrive für UNIX Stack

Sie müssen akzeptable Werte für das eingeben `_multipathing-type_`, `_fstype_`, `_default-transport_`, und `_vmtype_` Variablen in `snapdrive.conf` Datei wie im Matrix-Stack angegeben. Sie müssen überprüfen, ob die eingegebenen Werte in Ihrem Hostsystem installiert sind und ausgeführt werden.

|===
| Host-Plattform | Standardtransportart | Multipathing-Typ | Fstype | Vmtype 


 a| 
AIX
 a| 
FCP
 a| 
Keine
 a| 
jfs2
 a| 
lvm



 a| 
FCP
 a| 
Keine
 a| 
jfs
 a| 
lvm



 a| 
FCP
 a| 
Nativempio
 a| 
jfs2
 a| 
lvm



 a| 
FCP
 a| 
Nativempio
 a| 
jfs
 a| 
lvm



 a| 
FCP
 a| 
DMP
 a| 
vxfs
 a| 
vxvm

|===
* Wenn Sie FCP- und iSCSI-Storage-Stacks haben, unterstützt SnapDrive nur FCP Storage-Stacks.
+
SnapDrive unterstützt iSCSI Storage Stacks für AIX nicht.

* Das Host-Betriebssystem und die entsprechenden Patches für AIX sind installiert.
* Der Volumen-Manager für AIX ist LVM oder VxVM.
* Host Utilities sind in AIX installiert
+
Wenn Multipathing beispielsweise in SnapDrive für UNIX mit einem AIX-Host verwendet wird, müssen Sie die von den AIX-Host Utilities für diesen Host erforderlichen Funktionen einrichten.

* ONTAP Software ist auf Ihrem Storage-System installiert.
* Für eine Einrichtung der vFiler Einheit wird MultiStore Software auf Ihrem Storage-System installiert.
* Der Zugriff auf das Internet-Protokoll (IP) ist zwischen dem Host und dem Speichersystem möglich.


NetApp ändert regelmäßig Host Utilities und Komponenten. Diese Änderungen können Sie verfolgen, indem Sie die Interoperabilitäts-Matrix verwenden, die aktuelle Informationen zur Verwendung von NetApp Produkten in einer SAN-Umgebung enthält.

Die Lizenz des Storage-Systems und die Lizenz des MultiStore bilden die Einheiten des Storage-Systems.



== Lizenzierungsanforderungen für Storage-Systeme

* Eine FC-, iSCSI- oder NFS-Lizenz, je nach Konfiguration
* Eine FlexClone Lizenz
* Eine SnapRestore-Lizenz auf dem Storage-System


*Verwandte Informationen*

xref:concept_unable_to_select_a_storage_stack.adoc[Es kann kein Storage-Stack ausgewählt werden]

xref:concept_when_to_use_the_snapdrive_configuration_wizard.adoc[SnapDrive-Konfigurationsassistent]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"]
