---
permalink: aix/task_stopping_the_clone_and_lun_clone_split.html 
sidebar: sidebar 
keywords: snap, snapdrive, stop, volume, clone, split, operation 
summary: Sie können den Klon-Split für einen Volume-Klon oder LUN-Klon mit der Job-ID- oder Dateispezifikation beenden. 
---
= Beenden des Volume-Klons oder des LUN-Klonabtrennens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Klon-Split für einen Volume-Klon oder LUN-Klon mit der Job-ID- oder Dateispezifikation beenden.

.Schritte
. Geben Sie den folgenden Befehl ein:
+
`*snapdrive clone split stop [-lun] _long_lun_name_ [_long_lun_name_...] |[{-dg | -vg | -fs | -hostvol | -lvol} _file_spec_ [_file_spec_...]] | [-job _<jobid>_]*`

+
SnapDrive für UNIX stoppt den Vorgang zum Beenden der Klonabteilung, der gerade ausgeführt wird.



Im folgenden Beispiel wird der Vorgang zum Aufteilen von Klonen dargestellt, der durch Verwendung der Dateispezifikation angehalten wird.

[listing]
----
# snapdrive clone split stop -fs /mnt/my_mnt4 /mnt/my_mnt3
Clone-Split for "/mnt/my_mnt4" is 0% Completed and Stopped.
Clone-Split for "/mnt/my_mnt3" is 0% Completed and Stopped.
----
Im folgenden Beispiel wird der Split-Vorgang des Klons dargestellt, der mithilfe der Job-ID angehalten wird.

[listing]
----
# snapdrive clone split stop -job B265Dbv8gh
Clone-Split for "/mnt/my_mnt3" is 14% Completed and Stopped.
Clone-Split for "/mnt/my_mnt4" is 17% Completed and Stopped.
----
Das folgende Beispiel ist eine typische Ausgabe, die den Vorgang zum Beenden eines Klons für eine Dateispezifikation zeigt, die bereits angehalten ist.

[listing]
----
# snapdrive clone split stop -fs /mnt/my_mnt4 /mnt/my_mnt3
Clone-Split for "/mnt/my_mnt3" is not stopped : No split is in progress for this resource
Clone-Split for "/mnt/my_mnt4" is not stopped : No split is in progress for this resource
----
[NOTE]
====
* Wenn der Clone Split für eine bestimmte Dateispezifikation in der Job-id angehalten wird und der Clone-Split-Stopp erfolgreich ist, wird die Dateispezifikation aus dem Job entfernt.
* Wenn der Clone-Split für einen Job angehalten wird und der Clone-Split-Stopp für alle Dateispezifikation im Job erfolgreich ist, wird der Job aus dem Jobsatz entfernt.


====