---
permalink: aix/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy 
summary: Mit dem Befehl SnapDrive Snap show or list werden der Name des Storage-Systems angezeigt, zu dem die Snapshot Kopie erstellt wird, der Host-Name, das Datum und die Zeit usw. 
---
= Anzeigen einer Snapshot Kopie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Befehl `snapdrive snap show` Oder `list` Zeigt den Namen des Storage-Systems an, auf dem die Snapshot Kopie erstellt wird, den Host-Namen, das Datum und die Uhrzeit usw.

.Schritte
. Geben Sie die folgende Befehlssyntax ein, um eine Snapshot-Kopie anzuzeigen:
+
`*snapdrive snap show [-snapname] _long_snap_name_ [_snap_name_...] [-verbose]*`



Dieser Vorgang wird mindestens die folgenden Informationen über die Snapshot Kopie angezeigt:

* Der Name des Storage-Systems, auf dem die Snapshot Kopie erstellt wird
* Der Name des Hosts, der die Snapshot Kopie erstellt hat
* Der Pfad zu den LUNs auf dem Storage-System
* Das Datum und die Uhrzeit der Erstellung der Snapshot Kopie
* Der Name der Snapshot Kopie
* Die Namen der in der Snapshot-Kopie enthaltenen Festplattengruppen


*Beispiel*: Die folgenden Beispiele sind Beispiele von `snapdrive snap show` Befehl:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Beispiel*: In diesem Beispiel wird ein Platzhalter verwendet, um Informationen über die verfügbaren Snapshot Kopien auf einem bestimmten Volume anzuzeigen:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Beispiel*: In diesem Beispiel wird der `-verbose` Die Option wird in der Befehlszeile in einem AIX-Host verwendet:

[listing]
----
# snapdrive snap list betty:/vol/vol1:testsnap -v
snap name host date
snapped
------------------------------------------------------------------
-------------
betty:/vol/vol1:testsnap aix198-75 Jul 31
10:43 test1_SdDg
host OS: AIX 3 5
snapshot name: testsnap
Volume Manager: aixlvm 5.3
disk group: test1_SdDg
host volume: test1_SdHv
file system: test1_SdHv file system type: jfs2
mountpoint:
/mnt/test1
lun path dev paths
-------------------------------------------------------
betty:/vol/vol1/aix198-75_luntest1_SdLun /dev/hdisk32
----
*Beispiel*: Dieses Beispiel enthält Meldungen über Snapshot Kopien auf einem AIX-Host, die nicht mit SnapDrive für UNIX erstellt wurden:

[listing]
----
# snapdrive snap show -filer toaster
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:snap1 DBserver1 Oct 01 13:42 dg1
dg2
toaster:/vol/vol1:snap2 DBserver2 Oct 10 13:40
DBdg/hvol1
toaster:/vol/vol1:snap3 DBserver3 Oct 31 13:45
DBdg
----
In diesem Beispiel wird eine Snapshot Kopie eines LVM-basierten Dateisystems auf einem AIX-Host mit dem angezeigt `snapdrive snap show` Befehl und das `- verbose` Option:

[listing]
----
# snapdrive snap show -v -fs /mnt/check_submit/csdg2/hv3_0
snapname host date snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:mysnapshot sales-aix Aug 24 10:55 csdg2
host OS: AIX 1 5
snapshot name: mysnapshot
Volume Manager: aixlvm 5.1
disk group: csdg2
host volume: csdg2_log
host volume: csdg2_hv3_0
file system: csdg2_hv3_0 file system type: jfs2 mountpoint:
/mnt/check_submit/csdg2/hv3_0
lun path dev paths
-------------------------------------------------------
spinel:/vol/vol1/check_submit_aix-4 /dev/hdisk4
----
*Beispiel*: Die folgenden Beispiele verwenden Platzhalter:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Beispiel*: In diesem Beispiel ist die Verwendung eines Platzhalters ungültig, da der Platzhalter in der Mitte des Namens liegt, anstatt am Ende platziert zu werden:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----