---
permalink: aix/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, multipathing, hba 
summary: Um Multipathing in SnapDrive für UNIX zu verwenden, müssen Sie Schritte einschließlich der Installation und dem Starten des HBA durchführen. Wenn Sie eine Multipathing-Lösung von anderen Herstellern verwenden, müssen Sie die Software und das Anwendungspaket von der Website des HBA-Anbieters herunterladen. 
---
= Aktivieren von Multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Multipathing in SnapDrive für UNIX zu verwenden, müssen Sie Schritte einschließlich der Installation und dem Starten des HBA durchführen. Wenn Sie eine Multipathing-Lösung anderer Anbieter verwenden, müssen Sie die Software und das Applikationspaket auf der Website des HBA-Anbieters herunterladen.

Ihr System muss aktuelle Versionen von FC und iSCSI Systemkomponenten ausführen.

http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]

.Schritte
. Installieren Sie die unterstützten HBAs, bevor Sie die entsprechende Host Utilities-Software installieren.
+

NOTE: SnapDrive für UNIX unterstützt HBAs verschiedener Anbieter.

. Starten Sie den HBA-Service.
+
Wenn der HBA-Service nicht ausgeführt wird, wird die folgende Fehlermeldung angezeigt, wenn Sie SnapDrive für UNIX Befehle ausführen, z. B. `snapdrive storage create` Und `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
Sie müssen überprüfen, ob die erforderliche Anzahl an Pfaden in der Ausführung vorhanden ist. Sie können die Pfade mithilfe des Dienstprogramms sanlun überprüfen, das in der Software Host Utilities enthalten ist. Beispielsweise können Sie in der FC-Multipathing-Konfiguration die verwenden `sanlun fcp show adapter -v` Befehl.

+
Im folgenden Beispiel sind zwei HBA-Ports (fcd0 und fcd1) mit dem Host verbunden, die betriebsbereit sind (Portstatus). Sie können nur einen HBA oder iSCSI-Initiator haben und Sie müssen Multipathing konfigurieren, indem Sie mehr als einen Pfad zu den Ziel-LUNs bereitstellen.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Wenn Multipathing auf einem Host aktiviert ist, sind für dieselbe LUN mehrere Pfade sichtbar. Sie können das verwenden `sanlun lun show all` Befehl zum Überprüfen der Pfade: Im folgenden Beispiel können Sie mehrere Pfade zu derselben LUN finden (`fish: /vol/vol1/lun`):

+
[listing]
----
filer:         lun-pathname        device filename  adapter    protocol   lun size              lun state
    filer_1:        fish/vol/vol1/l1      hdisk36          fcs0       FCP       5m   (5242880)        GOOD
    filer_2:        fish/vol/vol0/lunKr   hdisk39          fcs0       FCP       100m (104857600)      GOOD
    filer_3:        fish/vol/vol0/testaix hdisk2           fcs0       FCP       200m (209715200)      GOOD
    filer_4:        fish/vol/vol1/l1      hdisk45          fcs1       FCP       5m   (5242880)        GOOD
----
. Zonen der Host-HBA-Ports und der Ziel-Ports in einer FC-Konfiguration mit der Switch-Zoning-Konfiguration.
. Installieren und richten Sie den entsprechenden FC- oder iSCSI-Switch ein.
. Stack-Anforderungen für SnapDrive für UNIX prüfen.
. Installation oder Upgrade von SnapDrive für UNIX
. Überprüfen Sie die Installation von SnapDrive für UNIX.
. Suchen Sie das `snapdrive.conf` Dateipfad:
. Konfigurieren Sie die folgenden Konfigurationsvariablen in der `snapdrive.conf` Datei:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Bei jedem Host hängen Multipathing-Typ, Transporttyp, Filesystem und Volume-Manager-Typ von einander ab. In der folgenden Tabelle werden alle möglichen Kombinationen beschrieben:



+
|===
| Host-Plattform | Standardtransportart | Multipathing-Typ | Fstype | Vmtype 


 a| 
AIX
 a| 
FCP
 a| 
Absolut
 a| 
jfs2 oder jfs
 a| 
lvm



 a| 
Nativempio
 a| 
jfs2 oder jfs
 a| 
lvm



 a| 
dmp
 a| 
vxfs
 a| 
vxvm

|===
+
Die vorstehende Tabelle gibt die unterstützten Werte des an `_multipathing-type_`, `_default-transport_`, `_fstype_`, und `_vmtype_` Konfigurationsvariablen.

. Speichern Sie die `snapdrive.conf` Datei:
+
SnapDrive für UNIX prüft diese Datei automatisch jedes Mal, wenn sie startet. Sie müssen den SnapDrive for UNIX Daemon neu starten, damit die Änderungen wirksam werden.



*Verwandte Informationen*

http://mysupport.netapp.com["NetApp Support"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["AIX Host Utilities 6.0 Installations- und Setup-Handbuch"]
