---
permalink: aix/task_connecting_to_asnapshot_copy_thatcontains_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, snapshot, copy, connect 
summary: Sie können mithilfe des Befehls SnapDrive Snap connect mit einer Snapshot Kopie, die LUNs enthält, eine Verbindung herstellen. 
---
= Verbindung mit einer Snapshot Kopie, die LUNs enthält, wird hergestellt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mithilfe von eine Snapshot Kopie, die LUNs enthält, mit einer Verbindung herstellen `snapdrive snap connect` Befehl.

.Schritte
. Geben Sie die folgende Befehlssyntax ein, um eine Verbindung zu einer Snapshot-Kopie herzustellen, die LUNs enthält:
+
`*snapdrive snap connect -lun _s_lun_name d_lun_name_ [[-lun] _s_lun_name d_lun_name_... -snapname _long_snap_name_ [-igroup _ig_name_ [_ig_name_...]] [-split]*`

+

NOTE: Die_s_lun_Name_ und _d_lun_Name_ sollten im Format lun_Name oder qtree_Name/lun_Name liegen.



SnapDrive für UNIX klont die von Ihnen angegebenen LUNs und verbindet sie mit einem neuen Speicherort.

Im folgenden Beispiel wird die LUN mylun1 unter hornet/vol/vol1/tuesdaySnapshot mit mylun1copy verbunden:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -snapname
hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1) mapping new lun(s) ... done
discovering new lun(s) ... done
----
Im folgenden Beispiel sind zwei LUNs, mylun1 und mylun2, mit mylun1copy bzw. mylun2copy verbunden:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -lun mylun2
mylun2copy -snapname hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1)
mapping new lun(s) ... done
connecting hornet:/vol/vol1/mylun2:
LUN copy mylun2copy ... created
(original: hornet:/vol/vol1/mylun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
----