---
permalink: solaris/concept_using_selective_lun_map_in_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, selective, lun, map 
summary: 'Ab Clustered Data ONTAP 8.3 ist die selektive LUN-Zuordnung \(SLM\) standardmäßig auf allen neuen LUN-Zuordnungen aktiviert. Wenn Sie eine neue LUN-Zuordnung erstellen, ist der Zugriff auf die LUN nur durch Pfade auf dem Node möglich, der der Eigentümer dieser LUN und seiner HA-Partner ist.' 
---
= Verwenden der Selective LUN Map in SnapDrive for UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab Clustered Data ONTAP 8.3 ist die selektive LUN-Zuordnung (Selective LUN Map, SLM) standardmäßig auf allen neuen LUN-Zuordnungen aktiviert. Wenn Sie eine neue LUN-Zuordnung erstellen, ist der Zugriff auf die LUN nur durch Pfade auf dem Node möglich, der der Eigentümer dieser LUN und seiner HA-Partner ist.

Standardmäßig sind die LUNs auf allen LIFs einer Storage Virtual Machine (SVM) zugänglich. Sie sollten den SVMs auf jedem Cluster-Node im Netzwerk LIFs zuweisen. Wenn die Anzahl der Nodes im Cluster steigt, erhöht sich auch die Anzahl der potenziellen Pfade. Dies kann zu einer übermäßigen Anzahl an Pfaden zu einer LUN, mehreren Initiatorgruppen pro Host und zu Unterbrechungen bei der Mobilität führen. SLM löst diese Probleme, indem die LUN-Verfügbarkeit auf den Node beschränkt wird, der Eigentümer der LUN und des HA-Partner-Node ist. Zudem erstellt es eine einzelne Initiatorgruppe pro Host und unterstützt unterbrechungsfreie LUN-Mobilitätsvorgänge, die keine portset-Manipulation oder LUN-Neuzuordnung erfordern.


NOTE: SLM gilt nicht automatisch für LUN-Zuordnungen, die vor Clustered Data ONTAP 8.3 erstellt wurden.

Wenn Sie über den Node, der das LUN besitzt, auf die LUN zugreifen, wird der Pfad „aktiv optimiert“ genannt. Wenn Sie jedoch über den HA Partner Node auf diese LUN zugreifen, wird der Pfad „aktiv nicht optimiert“ genannt.

|===
| SnapDrive-Befehl | Beschreibung 


 a| 
`snapdrive lun showpaths _long_lun_name_`
 a| 
Der `snapdrive lun showpaths` Mit dem Befehl werden alle Pfade zur LUN aufgeführt. Es zeigt auch an, welcher Pfad aktiv optimiert ist und welcher Pfad aktiv nicht optimiert ist.

`_long_lun_name_` Ist der Name der LUN. Wenn Sie die LUN nicht angeben, wird der Vorgang für alle LUNs durchgeführt.

[listing]
----
snapdrive lun showpaths
lun path            device filename                   asymmetric access state
------------------------------------------------------------------------------
vs1:/vol/vol2/lun10  /dev/mapper/3600a09807746505a4e24455450473655   Non-optimized
vs1:/vol/vol2/lun2  /dev/mapper/3600a09807746505a4d3f455432474b30    Optimized
vs1:/vol/vol2/lun1  /dev/mapper/3600a09807746505a4e24455450473656    Optimized
----


 a| 
`snapdrive lun fixpaths _long_lun_name_`
 a| 
Der `snapdrive lun fixpaths` Der Befehl versucht, den Pfad der LUNs für die LUNs zu korrigieren, die nicht mindestens einen aktiven optimierten Pfad aufweisen. `_long_lun_name_` Ist der Name der LUN. Wenn Sie die LUN nicht angeben, wird der Vorgang für alle LUNs durchgeführt, die nicht mindestens einen aktiven optimierten Pfad aufweisen.

[listing]
----
snapdrive lun fixpaths
The following LUNs are using Non-optimized paths
-------------------------------------------------
vs1:/vol/vol2/lun10

Path correction successful for the following LUNs
--------------------------------------------------
vs1:/vol/vol2/lun10
----

NOTE: Der `snapdrive lun fixpaths` Der Befehl funktioniert nicht im Gastbetriebssystem.

|===
Der `lunpath-monitor-frequency` Parameter ermöglicht Ihnen die Angabe der Häufigkeit, mit der SnapDrive für UNIX automatisch den Pfad für LUNs fixieren soll. Der Standardwert ist 24 Stunden.

Wenn der `snapdrive lun fixpaths` Der Vorgang schlägt fehl. Eine AutoSupport-Meldung (ASUP) wird für alle LUNs generiert. Die ASUP Meldung enthält folgende Details:

* Computername
* EventSource
* AppVersion
* EventID
* Kategorie
* Betreff


Nachfolgend das Beispiel einer ASUP Meldung:

[listing]
----
computerName="owhyee"
       eventSource="snapdrive"
       appVersion="5.2.2 for UNIX"
       eventID="6"
       category="lun path"
       subject="Paths are misconfigured for the Luns /vol/June12v1/LUN2 in storage system sdu_100_101_60_62_vs1 on owhyee host."
----
*Verwandte Informationen*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["ONTAP 9 – Systemadministrationshandbuch"]
