---
permalink: solaris/concept_operation_with_multiple_storage_objects.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, object, multiple, error 
summary: Das folgende Beispiel zeigt die Fehlermeldung, die Sie erhalten würden, wenn Sie kein autorisierter Benutzer sind, um die bestimmte Operation auszuführen. 
---
= Betrieb mit mehreren Storage-Objekten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das folgende Beispiel zeigt die Fehlermeldung, die Sie erhalten würden, wenn Sie kein autorisierter Benutzer sind, um die bestimmte Operation auszuführen.

[listing]
----
[john]$ snapdrive storage show –all

Connected LUNs and devices:

device filename   adapter  path  size  proto  state  clone  lun path                           backing Snapshot
----------------  -------  ----  ----  -----  -----  -----  --------                           ---------------
/dev/sdao            -     -     200m  iscsi  online  No    storage_array1:/vol/vol2/passlun1           -
/dev/sda1            -     -     200m  fcp    online  No    storage_array1:/vol/vol2/passlun2           -

Host devices and file systems:

dg: testfs1_SdDg                dgtype lvm
hostvol: /dev/mapper/testfs1_SdDg-testfs1_SdHv  state: AVAIL
fs: /dev/mapper/testfs1_SdDg-testfs1_SdHv       mount point: /mnt/testfs1 (persistent) fstype ufs

device filename   adapter  path  size  proto  state   clone  lun path                                backing Snapshot
----------------  -------  ----  ----  -----  -----   -----  --------                                ---------
/dev/sdn             -      P    108m  iscsi  online   No    storage_array1:/vol/vol2/testfs1_SdLun         -
/dev/sdn1             -      P    108m  fcp  online   No    storage_array1:/vol/vol2/testfs1_SdLun1         -

0002-719 Warning: SD.Storage.Read access denied on volume storage_array1:/vol/vol1 for user unix_host\john on Operations Manager server ops_mngr_server
----
John ist berechtigt, Storage-Einheiten auf vol2, aber nicht auf vol1 aufzulisten. SnapDrive für UNIX zeigt Einheiten von vol1 an und zeigt eine Warnmeldung für vol2 an.


NOTE: Für `storage list`, `storage show`, `snap list`, und `snap show` „Commands SnapDrive für UNIX“ zeigt eine Warnung anstelle von Fehlern an.
