---
permalink: solaris/concept_considerations_for_supporting_vfiler_unit.html 
sidebar: sidebar 
keywords: snap, snapdrive, vfiler, unit, support, issue 
summary: 'SnapDrive für UNIX unterstützt SnapDrive Operationen auf einer vFiler Einheit, die auf einem FlexVol Volume erstellt wurde. SnapDrive für UNIX unterstützt jedoch keine vFiler Einheiten, wenn Sie Fibre Channel \(FC\) verwenden.' 
---
= Support-Probleme bei der vFiler Einheit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX unterstützt SnapDrive Operationen auf einer vFiler Einheit, die auf einem FlexVol Volume erstellt wurde. SnapDrive für UNIX unterstützt jedoch keine vFiler Einheiten, wenn Sie Fibre Channel (FC) verwenden.

Beachten Sie einige Überlegungen in Bezug auf SnapDrive für UNIX, die vFiler Einheiten unterstützen:

* SnapDrive Vorgänge werden auf einer auf einem qtree erstellten vFiler Einheit nicht unterstützt.
+
Diese Vorgänge sind zulässig, wenn die Einheit vFiler Eigentümer des gesamten Storage Volume ist.

* Wenn Sie SnapDrive zur Unterstützung von vFiler Einheiten konfigurieren, müssen Sie sicherstellen, dass Management und Datenpfade nicht für eine Schnittstelle zu vFiler0 konfiguriert sind.


*Verwandte Informationen*

https://library.netapp.com/ecm/ecm_download_file/ECMP1511536["Data ONTAP 8.2 MultiStore Management Guide für 7-Mode"]
