---
permalink: solaris/concept_guidelines_forconnectingsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy 
summary: Beachten Sie beim Verbinden mit Snapshot Kopien die Richtlinien. 
---
= Richtlinien zum Verbinden von Snapshot Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beachten Sie beim Verbinden mit Snapshot Kopien die Richtlinien.

* Der `snapdrive snap connect` Befehl funktioniert nur mit den in SnapDrive 4.2 für UNIX erstellten Snapshot-Kopien.
* SnapDrive für UNIX unterstützt auf einem von Ursprung stammenden Host das Verbinden und Wiederherstellen von Snapshot Kopien, die von früheren Versionen von SnapDrive für UNIX erstellt wurden.
* Für Lese- und Schreibzugriff auf NFS Verzeichnisbäume, die `snapdrive snap connect` Befehl verwendet die Data ONTAP FlexVol-Volume-Funktion und erfordert daher Data ONTAP 7.3 oder höher. Konfigurationen mit Data ONTAP 7.1 können NFS-Dateien oder Verzeichnisbäume verbinden, werden aber mit schreibgeschütztem Zugriff bereitgestellt.
* Wenn Sie die einstellen `_enable-split-clone_` Wert der Konfigurationsvariable für „`on`“ oder „`sync`“ während der Verbindungsherstellung mit Snapshots und „`off`“ während der Momentabtrennung des Snapshots löscht SnapDrive für UNIX nicht das ursprüngliche Volume oder die ursprüngliche LUN, die sich in der Snapshot Kopie befindet.
* Sie müssen den Wert für die Data ONTAP 7.2.2-Konfigurationsoption vfiler festlegen. `vol_clone_zapi_allow` Zu „`auf`“, um eine Verbindung zu einer Snapshot Kopie eines Volume oder einer LUN in einer vFiler Einheit herzustellen.
* Der Snapshot-Verbindungsvorgang wird auf den Hosts mit unterschiedlichen Host-Konfigurationen nicht unterstützt.
* Der `snapdrive snap connect` Befehl, der für die Verbindung mit einem Root-Volume eines physischen Storage-Systems oder einer vFiler Einheit verwendet wird, schlägt fehl, da Data ONTAP das Klonen eines Root-Volumes nicht erlaubt.

