---
permalink: solaris/concept_automatic_detection_of_host_entities.html 
sidebar: sidebar 
keywords: snap, snapdrive, automatic, detection, host 
summary: SnapDrive für UNIX erkennt bei einigen Befehlen automatisch die Konfiguration der Host-Einheit. Ein paar Snap Storage Befehle benötigen nur den Namen der Host-Einheit. In diesen Fällen müssen Sie den Typ der Host-Einheit nicht angeben. 
---
= Automatische Erkennung von Host-Einheiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX erkennt bei einigen Befehlen automatisch die Konfiguration der Host-Einheit. Einige `snap storage` Befehle benötigen nur den Namen der Host-Einheit. In diesen Fällen müssen Sie den Typ der Host-Einheit nicht angeben.

Die folgenden Befehle sind für die automatische Erkennung aktiviert:

* `storage delete`
* `storage resize`
* `snap create`
* `snap restore`
* `snap connect`
* `snap list`


Wenn die Host-Einheit vorhanden ist, erkennt SnapDrive für UNIX automatisch den Typ der Host-Einheit. In diesem Fall müssen Sie nur den Namen der Host-Einheit angeben. Sie müssen den Typ nicht angeben. Das SnapDrive `snap` Befehle und einige `storage` Befehle benötigen auch nur den Namen der Host-Einheit. Sie müssen den Typ nicht angeben.

Das automatische Erkennen von Befehlen dauert für SnapDrive 4.1 und höher Extrazeit, da es alle Daten aller Speicherressourcen erfasst. Wenn Sie eine schnellere Antwort wünschen, geben Sie die Dateispezifikation mit den Befehlen SnapDrive für UNIX an.

Sie können die automatische Erkennung für den Speicherlösch aktivieren, indem Sie den ausführen `snapdrive storage delete` Befehl.

*Beispiel 1:*

[listing]
----
snapdrive storage delete host_dg my_fs -full
----
Im Beispiel `host_dg` Und `my_fs` Werden automatisch erkannt.

*Beispiel 2:*

[listing]
----
snapdrive storage delete mydg -fs myfs -full
----
In dem Beispiel wird der verwendet `mydg` Laufwerksgruppe wird automatisch erkannt.

Sie können die automatische Erkennung der Speichergröße aktivieren, indem Sie den ausführen `snapdrive storage resize` Befehl.

* Zum Beispiel*:

[listing]
----
[root@lnx197-132 ~]# snapdrive storage resize mydg23 -addlun -growby 10m
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
        discovering filer LUNs in disk group mydg23...done
        LUN bart:/vol/voldm/mydg23-1_SdLun ... created

        mapping new lun(s) ... done
        discovering new lun(s) ... done.
        initializing LUN(s) and adding to disk group mydg23...done
Disk group mydg23 has been resized
----
Sie können die automatische Erkennung für den Snap create-Vorgang aktivieren, indem Sie den ausführen `snapdrive snap create` Befehl.

* Zum Beispiel*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap create mydg22 mydg23 /mnt/mnt12 -snapname new_snap
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec '/mnt/mnt12 ' in progress ... detected as file system

Starting snap create /dev/mapper/mydg22, /dev/mapper/mydg23, /mnt/mnt12
  WARNING:  DO NOT CONTROL-C!
            If snap create is interrupted, incomplete snapdrive
                 generated data may remain on the filer volume(s)
                 which may interfere with other snap operations.
Successfully created snapshot new_snap on bart:/vol/voldm

        snapshot new_snap contains:
        disk group mydg22
        disk group mydg23
        disk group dg121 containing host volumes
                lv121 (filesystem: /mnt/mnt12)
----
Sie können die automatische Erkennung für den Snap-Connect-Betrieb aktivieren, indem Sie den ausführen `snapdrive snap connect` Befehl.

* Zum Beispiel*:

[listing]
----
[root@lnx197-132 ~]# snapdrive snap connect mydg22 xxx mydg23 yyy -snapname bart:/vol/voldm:snap_1
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'xxx' in progress ...
        xxx does not exist - Taking xxx as a destination to fspec mydg22Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec 'yyy' in progress ...
        yyy does not exist - Taking yyy as a destination to fspec mydg23
 connecting mydg22:
        LUN copy mydg22_SdLun_0 ... created
                 (original: bart:/vol/voldm/mydg22_SdLun)

        mapping new lun(s) ... done

 connecting mydg23:
        LUN copy mydg23_SdLun_1 ... created
                 (original: bart:/vol/voldm/mydg23_SdLun)

        mapping new lun(s) ... done
        discovering new lun(s) ... done
        Importing xxx, yyy
Successfully connected to snapshot bart:/vol/voldm:snap_1
        disk group xxx
        disk group yyy
----
Sie können die automatische Erkennung für den Snap-Restore-Vorgang aktivieren, indem Sie den ausführen `snapdrive snap restore` Befehl.

* Zum Beispiel*:

[listing]
----
snapdrive snap restore bart:/vol/voldm/lun44 /mnt/fs3 fs5_SdDg/fs5_SdHv fs4_SdDg -snapname bart:/vol/voldm:toi_snap

        Auto detection of file_spec(s) in progress ...
               - 'bart:/vol/voldm/lun44' detected as LUN.
               - '/mnt/fs3' detected as file system.
               - 'fs5_SdDg/fs5_SdHv' detected as logical volume.
               - 'fs4_SdDg' detected as disk group.
        Starting to restore /dev/mapper/fs4_SdDg, /mnt/fs3, /dev/mapper/fs5_SdDg-fs5_SdHv, bart:/vol/voldm/lun44
         WARNING:  This can take several minutes.
           DO NOT CONTROL-C!
           If snap restore is interrupted, the filespecs
           being restored may have inconsistent or corrupted
           data.
       For detailed progress information, see the log file /var/log/sd-recovery.log
           Importing fs4_SdDg, fs3_SdDg, fs5_SdDg
           Successfully restored snapshot toi_snap on bart:/vol/voldm
       disk group fs4_SdDg containing host volumes
               fs4_SdHv (filesystem: /mnt/fs4)
       disk group fs3_SdDg containing host volumes
               fs3_SdHv (filesystem: /mnt/fs3)
       disk group fs5_SdDg containing host volumes
               fs5_SdHv (filesystem: /mnt/fs5)
       raw LUN: bart:/vol/voldm/lun44
----
SnapDrive unterstützt nicht die automatische Erkennung von Snap Connect und Snap Restore Operationen für falsche Dateispezifikation.

Sie können die automatische Erkennung für den Snap-List-Betrieb aktivieren, indem Sie den ausführen `snapdrive snap list` Befehl.

* Zum Beispiel*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap list -snapname bart:/vol/voldm:snap_1

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
[root@lnx197-132 ~]# snapdrive snap list mydg23
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
bart:/vol/voldm:all                  lnx197-132.xyz.com Apr  9 00:16 mydg22 mydg23 fs1_SdDg
bart:/vol/voldm:you                  lnx197-132.xyz.com Apr  8 21:03 mydg22 mydg23
bart:/vol/voldm:snap_2                  lnx197-132.xyz.com Apr  8 18:05 mydg22 mydg23
----