---
permalink: solaris/concept_guidelines_for_thestorage_createoperation.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, create 
summary: Wenn Sie den Befehl SnapDrive Storage create zum Erstellen des Storage verwenden, sollten Sie bestimmte Richtlinien befolgen. 
---
= Richtlinien für den Speichervorgang erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie den Befehl SnapDrive Storage create für das verwenden, sollten Sie bestimmte Richtlinien befolgen `storage create` Betrieb.

* Wenn Sie LUNs aus verschiedenen Storage-System-Volumes mit auflisten `-lun` Option, Sie können die nicht einschließen `-dg`, `-hostvol`, Oder `-fs` Option an der Eingabeaufforderung.
* Der `-nolvm` Mit Option wird ein Dateisystem direkt auf einem LUN erstellt, ohne den Host LVM zu aktivieren.
+
Sie können keine Host-Volumes oder Datenträgergruppen angeben, wenn Sie diese Option verwenden.

* Sie können SnapDrive Befehle zur Bereitstellung von Storage für UNIX für NFS-Dateien oder Verzeichnisbäume nicht verwenden.
* Wenn Sie den verwenden `snapdrive storage create` Befehl zum Erstellen eines Dateisystems direkt auf einer LUN können Sie nicht mehr als eine LUN angeben.
+
SnapDrive für UNIX erstellt immer eine neue LUN, wenn Sie diese Form des Befehls verwenden.

* Einige Betriebssysteme verfügen über Einschränkungen für die Anzahl der LUNs, die Sie erstellen können.
+
Wenn auf Ihrem Host eines dieser Betriebssysteme ausgeführt wird, können Sie die ausführen `snapdrive config check luns` Befehl.

* Wenn sowohl UFS- als auch Veritas-Stacks installiert sind, sollten Sie den Wert verwenden `ufs` Mit dem `-fstype` Option zum Erstellen eines UFS-Dateisystems direkt auf einer LUN.
* Das Erstellen eines Filesystems auf einer RAW-LUN mit DMP-Multipathing wird unterstützt.


*Verwandte Informationen*

xref:concept_snapdrive_create_comand_fails_while_discovering_mapped_devices.adoc[Der Befehl zum Erstellen von SnapDrive für UNIX-Speicher schlägt beim Erkennen einiger zugeordneten Geräte fehl]

xref:concept_configuration_options_and_their_default_values.adoc[Konfigurationsoptionen und ihre Standardwerte]
