---
permalink: solaris/reference_host_side_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, host, side, command, line 
summary: SnapDrive für UNIX Befehle werden für hostseitige Vorgänge verwendet. 
---
= Host-seitige Befehlszeile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX Befehle werden für hostseitige Vorgänge verwendet.

Die folgende Tabelle bietet verschiedene Befehlszeilenoptionen für hostseitige Vorgänge.

|===
| Betrieb | Befehlszeilenoption 


 a| 
Host-Anbindung
 a| 
`snapdrive host connect -lun _long_lun_name_ [_lun_name ..._] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -nolvm -lun _long_lun_name_ [-nopersist][-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name_][-nopersist] [-mntopts _options_][-vmtype _type_]`



 a| 
Host-Verbindung trennen
 a| 
`snapdrive host disconnect-lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`



 a| 
`snapdrive host disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_[_file_spec_ ...][{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec_ ...]...] [-full] [-fstype _type_] [-vmtype _type_]`

|===