---
permalink: solaris/task_connecting_to_asnapshot_copy_thatcontains_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, lun 
summary: Sie können mithilfe des Befehls SnapDrive Snap connect mit einer Snapshot Kopie, die LUNs enthält, eine Verbindung herstellen. 
---
= Verbindung mit einer Snapshot Kopie, die LUNs enthält, wird hergestellt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mithilfe von eine Snapshot Kopie, die LUNs enthält, mit einer Verbindung herstellen `snapdrive snap connect` Befehl.

.Schritte
. Geben Sie die folgende Befehlssyntax ein, um eine Verbindung zu einer Snapshot-Kopie herzustellen, die LUNs enthält:
+
`*snapdrive snap connect -lun _s_lun_name d_lun_name_ [[-lun] _s_lun_name d_lun_name..._ -snapname _long_snap_name_ [-igroup _ig_name_ [_ig_name..._]] [-split]*`

+

NOTE: Der `_s_lun_name_` Und `_d_lun_name_` Sollte im Format „lun_Name“ oder „qtree_Name/lun_Name“ sein.



SnapDrive für UNIX klont die von Ihnen angegebenen LUNs und verbindet sie mit einem neuen Speicherort.

Im folgenden Beispiel wird die LUN mylun1 unter hornet/vol/vol1/tuesdaySnapshot mit mylun1copy verbunden:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -snapname
hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1) mapping new lun(s) ... done
discovering new lun(s) ... done
----
Im folgenden Beispiel sind zwei LUNs, mylun1 und mylun2, mit mylun1copy bzw. mylun2copy verbunden:

[listing]
----
# ./snapdrive snap connect -lun mylun1 mylun1copy -lun mylun2
mylun2copy -snapname hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1)
mapping new lun(s) ... done
connecting hornet:/vol/vol1/mylun2:
LUN copy mylun2copy ... created
(original: hornet:/vol/vol1/mylun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
----
Im folgenden Beispiel wird die LUN lun1_0 mit Snapshot lech:/vol/vol1:rrt verbunden:

[listing]
----

snapdrive snap connect -fs /mnt/fs /mnt/fs1  -snapname lech:/vol/vol1:rrt
connecting /mnt/fs:
   LUN copy lun1_0 ... created
     (original: lech:/vol/vol1/lun1)
   exporting new lun(s) to Guest OS ... done
   discovering new lun(s) ... done
Successfully connected to snapshot lech:/vol/vol1:rrt
        file system: /mnt/fs1
----