---
permalink: solaris/task_verifying_the_veritas_stack_configuration.html 
sidebar: sidebar 
keywords: snap, snapdrive, verify, veritas, stack, configuration 
summary: Um die Veritas Stack Konfiguration zu überprüfen, müssen Sie den SnapDrive Storage Connect und die vxdisk list Befehle ausführen. 
---
= Überprüfung der Veritas Stack-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur Überprüfung der Veritas-Stack-Konfiguration müssen Sie den ausführen `snapdrive storage connect` Und das `vxdisk list` Befehle.

Um die Konfiguration des Veritas Stacks zu überprüfen, müssen Sie zunächst bestätigen, dass Sie die folgenden Elemente in dieser Reihenfolge installiert haben:

. NTAPasl Bibliothek
. Veritas Lizenzen
. Veritas Stack (Storage-Grundlage)
. Multipathing-Lizenzen
. SnapDrive für UNIX Software


Führen Sie dann die folgenden Schritte aus:

.Schritte
. Geben Sie den folgenden Befehl ein, um eine Verbindung zu einem betriebssystemspezifischen Gerät herzustellen:
+
`*snapdrive storage connect -lun _long_lun_name_*`

+
Wobei der Name der lun lautet „long_lun_Name“.

. Geben Sie den folgenden Befehl ein, um die Geräteinformationen abzurufen:
+
`*vxdisk list*`



Möglicherweise erhalten Sie eines der folgenden Ergebnisse:

* Wenn die Veritas-Konfiguration auf dem Host korrekt ist, wird die erwartete Ausgabe für den Gerätestatus angezeigt
+
`online invalid.`

* Wenn die Veritas-Konfiguration auf dem Host falsch ist, wird die erwartete Ausgabe für den Gerätestatus angezeigt
+
`error.`

+
Diese Fehlermeldung erscheint, wenn Sie den Veritas Stack installieren, ohne die NTAPasl-Bibliothek zu installieren. Um diese Fehlermeldung zu beheben, müssen Sie die NTAPasl-Bibliothek installieren und den ausführen `vxinstall` Befehl zum Online-Modus der LUNs und Festplattengruppen.


