---
permalink: solaris/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy 
summary: Mit dem Befehl SnapDrive Snap show or list werden der Name des Storage-Systems angezeigt, zu dem die Snapshot Kopie erstellt wird, der Host-Name, das Datum und die Zeit usw. 
---
= Anzeigen einer Snapshot Kopie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Befehl `snapdrive snap show` Oder `list` Zeigt den Namen des Storage-Systems an, auf dem die Snapshot Kopie erstellt wird, den Host-Namen, das Datum und die Uhrzeit usw.

.Schritte
. Geben Sie die folgende Befehlssyntax ein, um eine Snapshot-Kopie anzuzeigen:
+
`*snapdrive snap show [-snapname] _long_snap_name_ [_snap_name_...] [-verbose]*`



Dieser Vorgang wird mindestens die folgenden Informationen 端ber die Snapshot Kopie angezeigt:

* Der Name des Storage-Systems, auf dem die Snapshot Kopie erstellt wird
* Der Name des Hosts, der die Snapshot Kopie erstellt hat
* Der Pfad zu den LUNs auf dem Storage-System
* Das Datum und die Uhrzeit der Erstellung der Snapshot Kopie
* Der Name der Snapshot Kopie
* Die Namen der in der Snapshot-Kopie enthaltenen Festplattengruppen


*Beispiel*: Die folgenden Beispiele sind Beispiele von `snapdrive snap show` Befehl:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Beispiel*: In diesem Beispiel wird ein Platzhalter verwendet, um Informationen 端ber die verf端gbaren Snapshot Kopien auf einem bestimmten Volume anzuzeigen:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Beispiel*: Die folgenden Beispiele verwenden Platzhalter:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Beispiel*: In diesem Beispiel ist die Verwendung eines Platzhalters ung端ltig, da der Platzhalter in der Mitte des Namens liegt, anstatt am Ende platziert zu werden:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----