---
permalink: solaris/task_considerations_for_provisioning_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, rdm, lun, provisioning 
summary: SnapDrive für UNIX verfügt über einige Überlegungen bei der Bereitstellung von RDM LUNs. 
---
= Überlegungen bei der Bereitstellung von RDM LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive für UNIX verfügt über einige Überlegungen bei der Bereitstellung von RDM LUNs.

* Überprüfen Sie die Konfigurationsvariable `_default-transport_` Variable wird als festgelegt `_fcp_` Im `snapdrive.conf` Datei im Gastbetriebssystem.
* Konfigurieren Sie SnapDrive für UNIX für den Zugriff auf die NetApp Virtual Storage Console für VMware vSphere.
* Stellen Sie sicher, dass die Konfigurationsvariablen für die Unterstützung von RDM LUNs in verwendet werden `snapdrive.conf` Datei: Die Variablen wie `_contact-viadmin-port_`, `_use-https-to-viadmin_`, `_vif-password-file and virtualization-operation-timeoutsecs=600_` Werden für die RDM LUN-Unterstützung verwendet.


*Verwandte Informationen*

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[Grenzen von RDM LUNs, die von SnapDrive gemanagt werden]

xref:concept_storage_provisioning_for_rdm_luns.adoc[VMware VMotion-Unterstützung in SnapDrive für UNIX]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[Konfiguration der Virtual Storage Console für SnapDrive für UNIX]

xref:concept_configuration_options_and_their_default_values.adoc[Konfigurationsoptionen und ihre Standardwerte]

xref:concept_guest_os_preparation_for_installing_sdu.adoc[Vorbereitung des Gastbetriebssystems für die Installation von SnapDrive für UNIX]
