---
permalink: solaris/task_connecting_tosnapshot_copies_ofshared_storageentities_other_thanluns.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, shared, storage, lun 
summary: Sie können den SnapDrive Snap connect Befehl verwenden, um eine Verbindung zu einer Snapshot Kopie von anderen Shared Storage-Einheiten als LUNs herzustellen. 
---
= Verbindung mit Snapshot Kopien von anderen Shared Storage-Einheiten als LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `snapdrive snap connect` Befehl zum Herstellen einer Verbindung zu einer Snapshot Kopie von anderen Shared Storage-Einheiten als LUNs.

.Schritte
. Geben Sie den folgenden Befehl ein:
+
`*snapdrive snap connect _fspec_set_ [_fspec_set..._] -snapname _long_snap_name_ [-devicetype shared] [-split]*`

+
In dieser Syntax `_fspec_set_` Ist: `{-dg | -fs}_src_file_spec_ [_dest_file_spec_ ] [-destdg _dgname_]`



Im folgenden Beispiel wird eine Verbindung zu einer Snapshot Kopie hergestellt, die Shared Storage-Einheiten auf einem aus einem ursprünglichen Host-Cluster enthält. Der Vorgang wird vom nicht-Cluster-Master-Node ausgeführt, der Befehl wird jedoch an den Master-Node gesendet und ausgeführt:

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting /mnt/sfortesting2 -
snapname f270-
197-109:/vol/vol2:testsfarcsnap -devicetype shared -autorename
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58 mapping lun\(s\) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d22s2
Importing sfortesting_SdDg_0
Activating hostvol sfracvxfstestfs_SdHv_0
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg_0 containing host volumes
sfortesting_SdHv_0 (filesystem: /mnt/sfortesting2)
----
Im folgenden Beispiel wird eine Verbindung zu einer Snapshot Kopie hergestellt, die Shared Storage-Einheiten auf einem nicht vom Ursprung stammenden Host-Cluster enthält. Der Vorgang wird vom nicht-Cluster-Master-Node ausgeführt, der Befehl wird jedoch an den Master-Node gesendet und ausgeführt:

[listing]
----
# snapdrive snap connect -fs /mnt/sfortesting -snapname f270-197-
109:/vol/vol2:testsfarcsnap -devicetype shared
Execution started on cluster master: sfrac-57
connecting sfortesting_SdDg:
LUN copy sfortesting_SdLun_0 ... created
(original: f270-197-109:/vol/vol2/sfortesting_SdLun)
Step Action
184 Connecting to a Snapshot copy
mapping new lun(s) ... done
discovering new lun(s) ... done
Connecting cluster node: sfrac-58
mapping lun(s) ... done
discovering lun(s) ... done
LUN f270-197-109:/vol/vol2/sfortesting_SdLun_0 connected
- device filename(s): /dev/vx/dmp/c3t0d1s2
Importing sfortesting_SdDg
Activating hostvol sfortesting_SdHv
Successfully connected to snapshot f270-197-
109:/vol/vol2:testsfarcsnap
disk group sfortesting_SdDg containing host volumes
sfortesting_SdHv (filesystem: /mnt/sfortesting)
----