---
permalink: solaris/task_deleting_a_user_login_for_a_virtual_storage_console.html 
sidebar: sidebar 
keywords: snap, snapdrive, delete, user, login, virtual, storage, console 
summary: Sie können eine Benutzeranmeldung einer virtuellen Schnittstelle löschen, indem Sie den Befehl SnapDrive config delete ausführen. 
---
= Löschen einer Benutzeranmeldung für eine virtuelle Speicherkonsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Benutzeranmeldung einer virtuellen Schnittstelle löschen, indem Sie die ausführen `snapdrive config delete` Befehl.

Stellen Sie sicher, dass Sie die Virtual Storage Console in vCenter konfiguriert haben.

.Schritte
. Geben Sie den folgenden Befehl ein:
+
`*snapdrive config delete _appliance_name_*`

+
`_appliance_name_` Ist der Name oder die IP-Adresse des virtuellen Schnittstellensystems.

+
SnapDrive für UNIX entfernt Benutzername oder Passwort-Anmeldeinformationen für die von Ihnen angegebene virtuelle Schnittstelle.

+

NOTE: Um SnapDrive für UNIX den Zugriff auf die virtuelle Schnittstelle zu aktivieren, müssen Sie eine neue Benutzeranmeldung angeben.


