---
permalink: solaris/task_configuring_user_credentials_on_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, configure, user, credential 
summary: Der SnapDrive für UNIX Administrator erhält vom Operations Manager Console Administrator Benutzeranmeldeinformationen. Diese Benutzerkennungen müssen auf SnapDrive für UNIX konfiguriert werden, damit sie ordnungsgemäß durchgeführt werden können. 
---
= Konfigurieren von Benutzeranmeldeinformationen auf SnapDrive für UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der SnapDrive für UNIX Administrator erhält vom Operations Manager Console Administrator Benutzeranmeldeinformationen. Diese Benutzerkennungen müssen auf SnapDrive für UNIX konfiguriert werden, damit sie ordnungsgemäß durchgeführt werden können.

.Schritte
. konfigurieren sie sd-Admin auf dem Speichersystem.
+
[listing]
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----
. konfigurieren sie den sd-Hostnamen auf dem Speichersystem.
+
[listing]
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----
. Überprüfen Sie Schritt 1 und Schritt 2 mit dem `snapdrive config list` Befehl.
+
[listing]
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----
. Konfiguration von SnapDrive für UNIX zur Nutzung der rollenbasierten Zugriffssteuerung (Role Based Access Control, RBAC) der Operations Manager Konsole durch Festlegen der Konfigurationsvariable `_rbac-method="dfm"_` Im `snapdrive.conf` Datei:
+

NOTE: Die Benutzeranmeldeinformationen werden verschlüsselt und in der vorhandenen gespeichert `.sdupw` Datei: Der Standardspeicherort der früheren Datei ist `/opt/ONTAPsnapdrive/.sdupw`.


